default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV["USER"]) %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: books_managmenet_development

test:
  <<: *default
  database: books_managmenet_test

production:
  primary: &primary_production
    <<: *default
    database: books_managmenet_production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: books_managmenet_production_cache
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: books_managmenet_production_queue
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: books_managmenet_production_cable
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
